[32mINFO    [0m root:test_OrangeHRM_Login.py:18 this is info
[33mWARNING [0m root:test_OrangeHRM_Login.py:19 this is warning
[31m[1mERROR   [0m root:test_OrangeHRM_Login.py:20 this is error
[31mCRITICAL[0m root:test_OrangeHRM_Login.py:21 this is critical
[31mCRITICAL[0m root:test_OrangeHRM_Login.py:22 started the test_orangehrm_url_001
[32mINFO    [0m root:test_OrangeHRM_Login.py:26 start loging
[32mINFO    [0m root:test_OrangeHRM_Login.py:28 opening browser
[32mINFO    [0m root:test_OrangeHRM_Login.py:32 test is pass
[32mINFO    [0m root:test_OrangeHRM_Login.py:41 test case is close
[32mINFO    [0m root:test_OrangeHRM_Login.py:43 test case is completed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0C4BA1690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/425e85913183010d513fbb04e006439d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0C4BA2050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/425e85913183010d513fbb04e006439d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0C4BA2950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/425e85913183010d513fbb04e006439d